// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/projetos.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProjetoServiceClient is the client API for ProjetoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProjetoServiceClient interface {
	ListarProjetos(ctx context.Context, in *ListarProjetosRequest, opts ...grpc.CallOption) (*ListarProjetosResponse, error)
}

type projetoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProjetoServiceClient(cc grpc.ClientConnInterface) ProjetoServiceClient {
	return &projetoServiceClient{cc}
}

func (c *projetoServiceClient) ListarProjetos(ctx context.Context, in *ListarProjetosRequest, opts ...grpc.CallOption) (*ListarProjetosResponse, error) {
	out := new(ListarProjetosResponse)
	err := c.cc.Invoke(ctx, "/projetos.ProjetoService/ListarProjetos", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjetoServiceServer is the server API for ProjetoService service.
// All implementations must embed UnimplementedProjetoServiceServer
// for forward compatibility
type ProjetoServiceServer interface {
	ListarProjetos(context.Context, *ListarProjetosRequest) (*ListarProjetosResponse, error)
	mustEmbedUnimplementedProjetoServiceServer()
}

// UnimplementedProjetoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProjetoServiceServer struct {
}

func (UnimplementedProjetoServiceServer) ListarProjetos(context.Context, *ListarProjetosRequest) (*ListarProjetosResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListarProjetos not implemented")
}
func (UnimplementedProjetoServiceServer) mustEmbedUnimplementedProjetoServiceServer() {}

// UnsafeProjetoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProjetoServiceServer will
// result in compilation errors.
type UnsafeProjetoServiceServer interface {
	mustEmbedUnimplementedProjetoServiceServer()
}

func RegisterProjetoServiceServer(s grpc.ServiceRegistrar, srv ProjetoServiceServer) {
	s.RegisterService(&ProjetoService_ServiceDesc, srv)
}

func _ProjetoService_ListarProjetos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListarProjetosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjetoServiceServer).ListarProjetos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/projetos.ProjetoService/ListarProjetos",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjetoServiceServer).ListarProjetos(ctx, req.(*ListarProjetosRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProjetoService_ServiceDesc is the grpc.ServiceDesc for ProjetoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProjetoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "projetos.ProjetoService",
	HandlerType: (*ProjetoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListarProjetos",
			Handler:    _ProjetoService_ListarProjetos_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/projetos.proto",
}
